### ISSUE TITLE
Does not load any verses

### ISSUE THREAD

**Issue by TomSipsOnCurry** [selfire1/BibleGateway-to-Obsidian#59]
I keep getting this error (MacOS 14.5)
```
ext/kernel_require.rb:54:in `require': cannot load such file -- colorize (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from bg2md.rb:77:in `<main>'
         Exodus —— Chapter 37 of 40 —— |▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩▩  | 92%^Z
```

**Comment by selfire1** [comment]
Have you tried running `sudo gem install colorize optparse clipboard`?

**Comment by selfire1** [comment]
I'll close this for now since additional details are required. Feel free to open another issue if this problem persists.
